---

# Services that can run as --user
- systemd: name={{ item }} state=started enabled=yes user=yes
  become: no
  with_items:
  - redshift-gtk
  - mpd


# Docker - create the docker group (gpasswd -a $USER docker)
# NB: this requires `newgrp docker` or logout
# DONT DO NEWGRP AS IT WILL SCREW WITH YOUR PRIMARY GROUP
- name: Add desktop user to docker group
  user: name={{desktop_user}} groups=docker append=yes

- systemd: name=docker state=started enabled=yes
